<?php
// api/v4/devices/register.php
// Epic 47: Register New Device

require_once __DIR__ . '/../../../includes/db_connect.php';
require_once __DIR__ . '/../../../api/auth_middleware.php'; // Basic auth to validate user exists
require_once __DIR__ . '/../../../includes/device_manager.php';
require_once __DIR__ . '/../../../includes/rate_limiter.php';

header('Content-Type: application/json');

try {
    // We assume an authenticated context (e.g., via a registration token or password exchange)
    // For this epic, we use standard auth but in real world this might be a fresh login flow.
    $authData = requireAuth();
    $userId = strtoupper($authData['user_id']);

    // Rate limit registration
    checkRateLimit($pdo, $userId, 'device_register', 10, 3600);

    $input = json_decode(file_get_contents('php://input'), true);

    // Device ID usually generated by client
    $deviceId = $input['device_id'] ?? '';
    $platform = $input['platform'] ?? '';
    $name = $input['device_name'] ?? 'Unknown Device';
    $identityKey = $input['identity_key'] ?? '';
    $preKey = $input['pre_key'] ?? '';

    if (!$deviceId || !$platform || !$identityKey || !$preKey) {
        http_response_code(400);
        echo json_encode(['error' => 'MISSING_PARAMS']);
        exit;
    }

    $result = registerDevice($pdo, $userId, $deviceId, $platform, $name, $identityKey, $preKey);

    echo json_encode(['success' => true, 'trust_state' => $result['status'], 'fingerprint' => $result['fingerprint']]);

} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['error' => 'SERVER_ERROR', 'message' => $e->getMessage()]);
}
